### ISSUE TITLE
Use created yaml state files as test data sources

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#78]
The idea is to enhance the state yaml file with assertions, something like this:

```yaml
decisions:
  - table: "table_name"
    outcome: "outcome_name"
    value: "expected value"
```

Then it will be possible to create an automated test run (usual JUnit stuff). It should be configurable from outside, like setting variables pointing to tables and tests folders.

The actual comparison could even be done with the help of EqualsCondition, lol
